CREATE TABLE IF NOT EXISTS ambuladb.CHAIN
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    status TINYINT NOT NULL,
    dateStatusChanged TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ambuladb.ACTIVITY
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(200) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ambuladb.NOEUD
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    dateStatusChanged TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM ('offline', 'not known', 'online')
);
