- name: Delete Linode Instance
  hosts: localhost
  vars:
      instance_label: "{{ 'ambula-' + linode_label }}"
  tasks:
      - name: Delete a Linode instance
        linode.cloud.instance:
            api_token: "{{ lookup('env', 'API_TOKEN') }}"
            label: "{{ instance_label }}"
            state: absent
