- name: Create Linode Instance
  hosts: localhost
  vars:
      instance_label: "{{ 'ambula-' + linode_label }}"
      ansible_python_interpreter: /root/miniconda3/bin/python3
  tasks:
      - name: Create a Linode instance
        linode.cloud.instance:
            api_token: "{{ lookup('env', 'API_TOKEN') }}"
            label: "{{ instance_label }}"
            type: g6-nanode-1
            region: us-east
            image: linode/ubuntu22.04
            state: present
        register: linode_instance

      - name: Wait for SSH to become available
        ansible.builtin.wait_for:
            host: "{{ linode_instance.instance.ipv4 }}"
            port: 22
            delay: 5
            timeout: 300
            state: started

      - name: Install Git
        ansible.builtin.apt:
            name: git
            state: present
            update_cache: yes

      - name: Clone the repository
        ansible.builtin.git:
            repo: "https://github.com/ambula-labs/ambula-shell-output-api.git"
            dest: "/home/ubuntu/ambula-shell-output-api"
            clone: yes
            force: yes
            version: main
            accept_hostkey: yes
            update: yes
            depth: 1
        become: yes
        become_user: ubuntu
