- name: Connect to remote machine via SSH and perform actions
  hosts: all
  gather_facts: false
  vars:
      root_password: "@Ambula123!"
  tasks:
      - name: Install Git
        ansible.builtin.apt:
            name: git
            state: present
            update_cache: yes
        become: yes

      - name: Clone the repository
        ansible.builtin.git:
            repo: "https://github.com/ambula-labs/ambula-shell-output-api.git"
            dest: "/ambula-shell-output-api"
            clone: yes
            force: yes
            version: main
            accept_hostkey: yes
            update: yes
            depth: 1
        become: yes
        become_user: root # Change to root or another user with sufficient privileges

      - name: Change to the repository directory
        ansible.builtin.command:
            cmd: cd /ambula-shell-output-api
        become: yes
        become_user: root

      - name: Install npm dependencies
        ansible.builtin.command:
            cmd: npm install
        become: yes
        become_user: root

      - name: Start the application
        ansible.builtin.command:
            cmd: npm start
        become: yes
        become_user: root
