- name: Connect to remote machine via SSH and perform actions
  hosts: all
  gather_facts: false
  vars:
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
      - name: Update package cache
        apt:
            update_cache: yes
        become: true
        become_method: sudo

      - name: Install Git
        apt:
            name: git
            state: present
        become: true
        become_method: sudo

      - name: Download Node.js binary package
        ansible.builtin.get_url:
            url: "https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz"
            dest: "/tmp/node-v18.16.0-linux-x64.tar.xz"
        become: yes

      - name: Extract Node.js package
        ansible.builtin.unarchive:
            src: "/tmp/node-v18.16.0-linux-x64.tar.xz"
            dest: "/usr/local"
            remote_src: yes
            extra_opts: "--strip-components=1"
        become: yes

      - name: Set Node.js environment variables
        ansible.builtin.lineinfile:
            path: /etc/profile.d/nodejs.sh
            line: "export PATH=$PATH:/usr/local/bin"
            create: yes
        become: yes

      - name: Install specific version of npm
        ansible.builtin.command:
            cmd: npm install -g npm
        become: yes
        become_user: root

      - name: Clone the repository
        ansible.builtin.git:
            repo: "https://github.com/ambula-labs/ambula-shell-output-api.git"
            dest: "/ambula-shell-output-api"
            clone: yes
            force: yes
            version: main
            accept_hostkey: yes
            update: yes
            depth: 1
        become: yes
        become_user: root # Change to root or another user with sufficient privileges

      - name: Install npm dependencies
        ansible.builtin.command:
            cmd: npm install
            chdir: /ambula-shell-output-api
        become: yes
        become_user: root

      - name: Start the application
        ansible.builtin.shell:
            cmd: npm start &
            chdir: /ambula-shell-output-api
        async: 300
        poll: 0
        become: yes
        become_user: root
